DROP TABLE `FATO_VENDA` CASCADE CONSTRAINTS;
DROP TABLE `DIM_CLIENTE` CASCADE CONSTRAINTS;
DROP TABLE `DIM_PRODUTO` CASCADE CONSTRAINTS;
DROP TABLE `DIM_LOCALIDADE` CASCADE CONSTRAINTS;
DROP TABLE `DIM_TEMPO` CASCADE CONSTRAINTS;

CREATE TABLE `FATO_VENDA` (
    `SK_CLIENTE` INTEGER(20) NOT NULL,
    `SK_PRODUTO` INTEGER(20) NOT NULL,
    `SK_LOCALIDADE` INTEGER(20) NOT NULL,
    `SK_DATA` INTEGER(20) NOT NULL,
    `VL_VENDA` DECIMAL NOT NULL,
    `QTD_VENDA` INTEGER NOT NULL,
    PRIMARY KEY (`SK_CLIENTE`, `SK_PRODUTO`, `SK_LOCALIDADE`, `SK_DATA`)
);

CREATE TABLE `DIM_CLIENTE` (
    `SK_CLIENTE` INTEGER(20) NOT NULL,
    `NK_ID_CLIENTE` VARCHAR(20) NOT NULL,
    `NM_CLIENTE` VARCHAR(50) NOT NULL,
    `NM_CIDADE_CLIENTE` VARCHAR(50) NOT NULL,
    `BY_ACEITA_CAMPANHA` BINARY NOT NULL,
    `DESC_CEP` VARCHAR(10) NOT NULL,
    PRIMARY KEY (`SK_CLIENTE`)
);

CREATE TABLE `DIM_PRODUTO` (
    `SK_PRODUTO` INTEGER(20) NOT NULL,
    `NK_ID_PRODUTO` VARCHAR(20) NOT NULL,
    `DESC_SKU` VARCHAR(50) NOT NULL,
    `NM_PRODUTO` VARCHAR(50) NOT NULL,
    `NM_CATEGORIA_PRODUTO` VARCHAR(30) NOT NULL,
    `NM_MARCA_PRODUTO` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`SK_PRODUTO`)
);

CREATE TABLE `DIM_LOCALIDADE` (
    `SK_LOCALIDADE` INTEGER(20) NOT NULL,
    `NK_ID_LOCALIDADE` VARCHAR(20) NOT NULL,
    `NM_LOCALIDADE` VARCHAR(50) NOT NULL,
    `NM_CIDADE_LOCALIDADE` VARCHAR(50) NOT NULL,
    `NM_REGIAO_LOCALIDADE` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`SK_LOCALIDADE`)
);

CREATE TABLE `DIM_TEMPO` (
    `SK_DATA` INTEGER(20) NOT NULL,
    `DATA` DATE NOT NULL,
    `DESC_DATA_COMPLETA` VARCHAR(50) NOT NULL,
    `NR_ANO` INTEGER(4) NOT NULL,
    `NM_TRIMESTRE` VARCHAR(20) NOT NULL,
    `NR_MES` INTEGER NOT NULL,
    `NM_MES` VARCHAR(20) NOT NULL,
    `NR_SEMANA` INTEGER NOT NULL,
    `NM_ANO_SEMANA` VARCHAR(20) NOT NULL,
    `NR_DIA` INTEGER NOT NULL,
    `NM_DIA_SEMANA` VARCHAR(20) NOT NULL,
    `FLAG_FERIADO` CHAR(3) NOT NULL,
    `NM_FERIADO` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`SK_DATA`)
);
